{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "rop-fsm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.funczz",
          "module": "rop",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rop-fsm-1.0.0.jar",
          "url": "rop-fsm-1.0.0.jar",
          "size": 33886,
          "sha512": "16abd0a220805c899bd6a3ff82154e2b64056f504dcf8906ca95f7584d16c31149b43feeeaa0171f7542c6978e12699d5bc0dd2e7b4e6c87cdc95befefac34e5",
          "sha256": "daf5cbeaaa81c55ba1f48452a517cb61223aea5e3d7419483b22b66b66fe046c",
          "sha1": "594c41d02efab96870bcf73ec935b22d2ed17d4d",
          "md5": "0ba66daa690ccbf6ba9911a022f1f6c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.funczz",
          "module": "rop",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rop-fsm-1.0.0.jar",
          "url": "rop-fsm-1.0.0.jar",
          "size": 33886,
          "sha512": "16abd0a220805c899bd6a3ff82154e2b64056f504dcf8906ca95f7584d16c31149b43feeeaa0171f7542c6978e12699d5bc0dd2e7b4e6c87cdc95befefac34e5",
          "sha256": "daf5cbeaaa81c55ba1f48452a517cb61223aea5e3d7419483b22b66b66fe046c",
          "sha1": "594c41d02efab96870bcf73ec935b22d2ed17d4d",
          "md5": "0ba66daa690ccbf6ba9911a022f1f6c3"
        }
      ]
    }
  ]
}
